version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      
  # Maintain depedencies for Bundler
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
