# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
#theme: jekyll-theme-so-simple
destination: docs/

remote_theme: mmistakes/so-simple-theme@3.2.0
skin: "/assets/css/skins/default.css"
locale: en-US
title: "Christopher Fiola"
description: "Speed skating sprint specialist aiming for Milano Cortina 2026"
baseurl: "/"
url: #"https://chrisfiola.github.io"
logo: "/images/skating.jpg" #/images/so-simple-site-logo.png" # path of site logo, e.g. "/assets/images/logo.png"
date_format: "%B %-d, %Y"
read_time: true
words_per_minute: 200
mathjax:
  enable: true
#  combo: "tex-mml-chtml"
#  tags: "none"
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
google_analytics: # Google Analytics id, e.g. "UA-NNNNNNNN-N"
disqus:
  shortname: "christopherfiola"
twitter:
  username: "chrisfiola" # site's Twitter username

# Liquid
liquid:
  error_mode: strict

# Build settings
markdown: kramdown
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Search
search_full_content: false

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Disable safe mode
safe: false

plugins:
  - jekyll-get-json
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  
#JSON Fetch
jekyll_get_json:
  - data: cat
    json: 'https://catfact.ninja/fact'
  - data: results
    json: 'https://speedskatingresults.com/api/json/personal_records?skater=46453'

# Collections
collections:
  updates:
    output: true
    permalink: /:collection/:path/
  hof:
    output: true
    permalink: /:collection/:path/
  wip:
    output: true
    permalink: /:collection/:path/

# Front Matter Defaults
defaults:
  # What's up
  - 
    scope:
      path: "_updates"
      type: updates
    values:
      layout: post
      comments: true
      share: true
  # Hall Of Fame
  - 
    scope:
      path: "_hof"
      type: hof
    values:
      layout: page
      comments: true
      share: true
  # Work In Progress
  - 
    scope:
      path: "_wip"
      type: wip
    values:
      layout: post
      comments: true
      share: true

# Site Author
author:
  name: Christopher Fiola
  picture: /images/myface.jpeg
  email: christopherfiola@gmail.com
  twitter: chrisfiola
  links:
    - title: Twitter
      url: https://twitter.com/chrisfiola
      icon: fab fa-twitter-square
    - title: Instagram
      url: https://instagram.com/chrisfiola
      icon: fab fa-instagram
    - title: GitHub
      url: https://github.com/chrisfiola
      icon: fab fa-github-square

# Footer Links
footer_links:
  - title: Twitter
    url: https://twitter.com/chrisfiola
    icon: fab fa-twitter-square
  - title: Instagram
    url: https://instagram.com/chrisfiola
    icon: fab fa-instagram
  - title: GitHub
    url: https://github.com/chrisfiola
    icon: fab fa-github-square
  - title: Feed
    url: https://www.facebook.com/chrisfiolacan
    icon: fab fa-facebook-square
